language: go

go:
  - 1.4
  - 1.5
  - tip

services:
  - rabbitmq


install:
  - go get -t
  - wget https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
  - unzip 0.5.2_linux_amd64.zip
  - wget https://dl.bintray.com/mitchellh/consul/0.5.2_web_ui.zip
  - unzip 0.5.2_web_ui.zip
  - mv dist /tmp/web-ui

script:
  - go test ./... -v
  - go build
