
endpoints:
  -
    name: Bar
    uri: /bar
    queuename: demo.bar
    servicehost: http://localhost:8080
  -
    name: Foo
    queuename: demo.foo
    servicehost: http://localhost:8080
    uri: /foo
