connection:
  user: guest
  password: guest
  host: localhost
  port: 5672

endpoints:
  -
    name: Foo
    queuename: demo.foo
    servicehost: http://localhost:8080
    uri: /foo
    method: POST
  -
    name: Slow 
    queuename: demo.slow
    servicehost: http://localhost:8080
    uri: /slow
    method: POST
disabled:
  -
    name: Bar
    queuename: demo.bar
    servicehost: http://localhost:8080
    uri: /bar
    method: POST
  -
    name: Bad 
    queuename: demo.bad
    servicehost: http://localhost:8080
    uri: /bad
    method: POST
  -
    name: RealBad 
    queuename: demo.realbad
    servicehost: http://localhost:9876
    uri: /dneaddy
    method: POST
