
endpoints:
  -
    name: Bar
    queuename: demo.bar
    servicehost: http://localhost:8080
    uri: /bar
    method: POST
  -
    name: Foo
    queuename: demo.foo
    servicehost: http://localhost:8080
    uri: /foo
    method: POST
  -
    name: Bad 
    queuename: demo.bad
    servicehost: http://localhost:8080
    uri: /bad
    method: POST
  -
    name: RealBad 
    queuename: demo.realbad
    servicehost: http://localhost:9876
    uri: /dneaddy
    method: POST
